// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nugget.Infrastructure.Data;

#nullable disable

namespace Nugget.Infrastructure.Migrations
{
    [DbContext(typeof(NuggetDbContext))]
    [Migration("20260210193746_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Nugget.Core.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Nugget.Core.Entities.NotificationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string>("DaysBeforeDue")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("days_before_due");

                    b.Property<int>("NotificationHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(9)
                        .HasColumnName("notification_hour");

                    b.Property<bool>("SlackNotificationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("slack_notification_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("notification_settings", (string)null);
                });

            modelBuilder.Entity("Nugget.Core.Entities.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date");

                    b.Property<bool>("NotifyImmediately")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_immediately");

                    b.PrimitiveCollection<string>("ReminderDays")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reminder_days");

                    b.Property<string>("TargetAttributeKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("target_attribute_key");

                    b.Property<string>("TargetAttributeValue")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("target_attribute_value");

                    b.Property<Guid?>("TargetGroupId")
                        .HasColumnType("char(36)")
                        .HasColumnName("target_group_id");

                    b.Property<string>("TargetGroupName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("target_group_name");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("target_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DueDate");

                    b.HasIndex("TargetGroupId");

                    b.ToTable("todos", (string)null);
                });

            modelBuilder.Entity("Nugget.Core.Entities.TodoAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<DateTime?>("LastNotifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_notified_at");

                    b.Property<Guid>("TodoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("todo_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TodoId", "UserId")
                        .IsUnique();

                    b.ToTable("todo_assignments", (string)null);
                });

            modelBuilder.Entity("Nugget.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("cost_center");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("department");

                    b.Property<string>("Division")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("division");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("employee_number");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("job_title");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("Organization")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("organization");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("SamlNameId")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("saml_name_id");

                    b.Property<string>("SlackUserId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("slack_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Department");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalId");

                    b.HasIndex("SamlNameId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Nugget.Core.Entities.UserGroup", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)")
                        .HasColumnName("group_id");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("user_groups", (string)null);
                });

            modelBuilder.Entity("Nugget.Core.Entities.NotificationSetting", b =>
                {
                    b.HasOne("Nugget.Core.Entities.User", "User")
                        .WithOne("NotificationSetting")
                        .HasForeignKey("Nugget.Core.Entities.NotificationSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nugget.Core.Entities.Todo", b =>
                {
                    b.HasOne("Nugget.Core.Entities.User", "CreatedBy")
                        .WithMany("CreatedTodos")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nugget.Core.Entities.Group", "TargetGroup")
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("Nugget.Core.Entities.TodoAssignment", b =>
                {
                    b.HasOne("Nugget.Core.Entities.Todo", "Todo")
                        .WithMany("Assignments")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nugget.Core.Entities.User", "User")
                        .WithMany("Assignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Todo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nugget.Core.Entities.UserGroup", b =>
                {
                    b.HasOne("Nugget.Core.Entities.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nugget.Core.Entities.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nugget.Core.Entities.Group", b =>
                {
                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Nugget.Core.Entities.Todo", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Nugget.Core.Entities.User", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("CreatedTodos");

                    b.Navigation("NotificationSetting");

                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
